
version: 2

models:
  - name: read_new_data
    description: "Incoming data from customer"
    columns:
      - name: first_name
        description: "The first name"
      - name: last_name
        description: "The last name"
      - name: email
        description: "The email"
      - name: phone
        description: "The phone"
      - name: street_address
        description: "The street address"
      - name: city
        description: "The city"
      - name: country
        description: "The country"
      - name: company_name
        description: "The company name"
      - name: department
        description: "The department"
      - name: job_title
        description: "The job title"
      - name: money_bank_account
        description: "The amount of money this customer has in their bank account."
  - name: transform
    description: "Cleanup strings and validate emails"
    columns:
      - name: id
        description: "Unique ID per Name combination"
      - name: full_name
        description: "The full name of the customer"
      - name: email
        description: "The email"
      - name: phone
        description: "The phone"
      - name: street_address
        description: "The street address"
      - name: city
        description: "The city"
      - name: country
        description: "The country"
      - name: company_name
        description: "The company name"
      - name: department
        description: "The department"
      - name: job_title
        description: "The job title"
      - name: money_bank_account
        description: "The amount of money this customer has in their bank account."
